New list models
CometVisu/CometVisu pull request #1289
Opened 2022-10-11 15:05 UTC by peuter

closes #1288

2022-10-30 22:10 UTC, ChristianMayer commented
Does this PR need an update due to the switch to Qx7?

2022-10-31 07:38 UTC, peuter commented
I did a rebase here now and found some lint errors regarding the last changes in the qx7 branch. so I enabled that the ci lint fails when there are linter errors (had been disabled to weit for qx7, now we can use it again).

2022-11-01 17:36 UTC, ChristianMayer requested changes
Apart from the comments we should discuss a general design decision: what is a plugin and what isn't.

The idea behind a plugin is (was) to have "fat" code that not everyone needs separated, so that only those who need it have to pay the price for it (load time, data and memory consumption). This also includes cases where you need more than the minimum setup - which traditionally was a static web server that has no PHP. (The "ideal" low end platform was a patched Fritz!Box).

This is the reason why the TR064/FritzBox and RSSLog are plugins - they can not live without PHP and also not everyone needs the functionality.
Including the "listmodel"s for those in the main code and not in a plugin is eroding the rule set for plugins. 
When those should stay in the main code then the consequence should be that TR064 and RSSLog are also moved to the main code and their status as a plugin should be stopped.

2022-11-01 17:36 UTC, ChristianMayer commented on source/resource/visu_config_tile.xsd
> +                <xsd:documentation xml:lang="de">Spezielles Listenmodell, die die CometVisu mitliefert.</xsd:documentation>
Grammatik-Fehler

2022-11-01 17:36 UTC, ChristianMayer commented on source/resource/visu_config_tile.xsd
> +                <xsd:documentation xml:lang="de">Parameter for die class Listenmodelle.</xsd:documentation>
`for`

2022-11-01 17:36 UTC, ChristianMayer commented on doc/manual/de/config/structure-tile/components/list.rst
> +Die CometVisu liefert einige vordefinierte Modell mit, mit denen einige Datenquellen von Plugins eingebunden werden
Modell -> Modelle

2022-11-01 17:36 UTC, ChristianMayer commented on doc/manual/de/config/structure-tile/components/list.rst
> +Die CometVisu liefert einige vordefinierte Modell mit, mit denen einige Datenquellen von Plugins eingebunden werden
das zweite "einige" besser entfernen

2022-11-01 17:36 UTC, ChristianMayer commented on doc/manual/de/config/structure-tile/components/list.rst
> +können. Bisher sind das die Anrufliste einer Fritz!Box über das :doc:`tr064 <../../widgets/plugins/tr064/index>`-Plugin und die Daten aus der
"Bisher sind das die Anrufliste" klingt komisch

2022-11-01 17:36 UTC, ChristianMayer commented on doc/manual/de/config/structure-tile/components/list.rst
> +es werden nur die Daten abgefragt und ansonsten nichts von den Plugins selbst benutzt.
Was ist mit der Hidden-Config? Die muss doch vermutlich korrekt befüllt sein, denn sonst weiß die Plugin-Datenquelle ja nicht wo sie nachfragen soll

2022-11-01 18:28 UTC, peuter commented
I am aware of the reasons for moving code into a plugin. The tile-structure currently does not support any of the existing plugins and I currently don't have any plans to change that (although that decision might change in the future). If it is useful I would prefer to provide that functionality "built-in". There are other ways to keep avoid bloating up the code base. For example the Tile-Charts only load the library for rendering a chart if you use it, so there is no need for the user to explicitly "activate" a plugin like its done in the pure-structure. And that is what I want to achieve here -> avoiding that extra step for the user. Also I think charts are a basic requirement for modern smart-home UIs so its a builtin feature of the tile structure. Loading data from external sources is another basic requirement (and that is what the list-models are made for). They do not add much code, so there is no need to move them to an extra peace of code that need to be additionally loaded.

So the only remaining valid reason to move the listmodels in an plugin, is that you need PHP support for that. If you use openHABs internal webserver for example these list models will not work because of that. But that can be detected automatically. I am preparing another pull request with changes for openhab specific stuff (also one for openhabs codebase). That one will enable detecting that the CometVisu is delivered by openHAB. When that is merged, the next step would be to inform the user about that when he tries to use the list models (and of course also document that information) and in addition detecting that there is no PHP support (in non openhab use case) by checking the response of the already existing request to environment.php. Although the last step could already be done right now, I would prefer to do it in the order I just described here.

So long story short: The tile-structure does not support plugins (on purpose), so I cannot move it to one. And the check for PHP-Support that is needed for these list-models will be delivered in future pull requests.

2022-11-01 22:27 UTC, ChristianMayer approved these changes

2022-11-01 22:27 UTC, merged