Feature client ID and fix bus initiated page switch
CometVisu/CometVisu pull request #1396
Opened 2024-01-14 23:09 UTC by ChristianMayer

- fix page switch by bus message; add transform instead of hard coded value
- implement client ID
- make page switch by bus message selective to client ID

2024-01-15 16:04 UTC, peuter requested changes

2024-01-15 16:08 UTC, peuter requested changes
This also breaks a unit test in page-spec.js -> `it('should test the page update'...`

2024-01-15 22:00 UTC, ChristianMayer commented on doc/manual/de/config/widgets/page/index.rst
> +    zukünftigen Versionen nicht mehr unterstützt werden.
Naja, das war schon immer unsauber. Daher der Hinweis das so nicht (mehr) zu machen.

Wenn das Ganze in ein `<address>` wandert muss der Text eh nochmal angepasst werden. So ist's halt eine 80% Lösung, die im Zweifel als Provisorium auch sehr lange halten könnte. (Und wenn es das `<address>` gibt, dann muss auch die Lib-Version hochgezogen werden und wir brauchen ein Konverter-Skript. Da wäre es schon sehr wünschenswert, wenn es schon eine fertige `transform` gibt, die man nutzen kann)

2024-01-16 19:10 UTC, peuter commented
Unit test is still not fixed, the whole `__inhibitGA4Startup` is the problem here. If its just to avoid the initial update call I think this would be the better solution.

```diff
diff --git a/source/class/cv/ui/common/Update.js b/source/class/cv/ui/common/Update.js
index 3e44264302..2f2cc6d7c2 100644
--- a/source/class/cv/ui/common/Update.js
+++ b/source/class/cv/ui/common/Update.js
@@ -46,6 +46,7 @@ qx.Mixin.define('cv.ui.common.Update', {
   */
   members: {
     _initOnCreate: false,
+    _skipInitialUpdate: false,

     __initUpdater() {
       const model = cv.data.Model.getInstance();
@@ -58,7 +59,7 @@ qx.Mixin.define('cv.ui.common.Update', {
           return;
         }
         const state = model.getState(address);
-        if (state !== undefined) {
+        if (!this._skipInitialUpdate && state !== undefined) {
           this.update(address, state);
         }
         //add listener
diff --git a/source/class/cv/ui/structure/pure/Page.js b/source/class/cv/ui/structure/pure/Page.js
index e0925eae27..329d5f7676 100644
--- a/source/class/cv/ui/structure/pure/Page.js
+++ b/source/class/cv/ui/structure/pure/Page.js
@@ -40,12 +40,6 @@ qx.Class.define('cv.ui.structure.pure.Page', {

     this.addListener('changeVisible', this._onChangeVisible, this);

-    // prevent listening to the first message to the GA in the first second
-    // as it might be of the trigger type and still be in the knxd cache
-    this.__inhibitGA4Startup = setTimeout(() => {
-      this.__inhibitGA4Startup = null;
-    }, 1000);
-
     // break out of the constructor
     new qx.util.DeferredCall(function () {
       const parentPage = this.getParentPage();
@@ -81,6 +75,7 @@ qx.Class.define('cv.ui.structure.pure.Page', {

     if (this.getAddress()) {
       this._initOnCreate = true;
+      this._skipInitialUpdate = true;
     }
   },

@@ -186,7 +181,6 @@ qx.Class.define('cv.ui.structure.pure.Page', {
     __waitForProperties: null,
     __colspanClass: null,
     __normalizedDomId: null,
-    __inhibitGA4Startup: null,

     _applyNavbarVisibility(value, old, name) {
       if (value !== null) {
@@ -332,13 +326,6 @@ qx.Class.define('cv.ui.structure.pure.Page', {
       //
       //   default:

-      if (this.__inhibitGA4Startup !== null) {
-        // ignore first bus message during this timeout
-        clearTimeout(this.__inhibitGA4Startup);
-        this.__inhibitGA4Startup = null;
-        return;
-      }
-
       const value = this.applyTransform(address, data);
       const filters = this.getAddress()[address]?.clients ?? '';
       let filterMatch = parseInt(data) === 1; // fallback for old behavior
```

2024-01-18 16:45 UTC, peuter approved these changes

2024-01-18 16:46 UTC, merged